### ISSUE TITLE
Training with Gatsbyjs tutorials

### ISSUE THREAD

**Issue by lauthieb** [sentaku-io/sentaku-io-website#2]
Official tutorial : https://www.gatsbyjs.org/tutorial/
Pretty cool tutorial on Youtube : https://www.youtube.com/watch?v=b2H7fWhQcdE&list=PLLnpHn493BHHfoINKLELxDch3uJlSapxg
Styled components : https://www.gatsbyjs.org/docs/styled-components/

**Comment by FlorianDuquesne** [comment]
Ok i ll do this tutorial this evening !

**Comment by lauthieb** [comment]
FYI : https://www.youtube.com/watch?v=b2H7fWhQcdE&list=PLLnpHn493BHHfoINKLELxDch3uJlSapxg
Tutorial pretty cool and simple ;)
